import random, string

obliqueinclinedslantedskewslopingsuspicious="".join(
    
    
    
    
    

    
    
    
    
    
    
    
    random.
    
    
    
    
    
    
                                                                                                                                                                                    choices(string
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
                                                                    .ascii_letters,
                
                
                
                
                
                
                
                
                
                k=42069 )) # very the funny

amogussusosuzsissomGFIOASJNOADSN = ['啊', '吧', '从', '的', '额', '发', '给', '和', 'i', '就', '有', '哦', '了', '吗', '你', '哦', '怕', '去', '人', '身', '体', '我', '下', '在', '有']

for x in __builtins__["range"](int(
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
string.













                                                                                digits











                                                                                                                [1]
















                                                )



















                                                                ,345345345, 420
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                                                                                                                        ):
    print(""
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
                                                        .join(
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            
                                                            __import__
                                                                   .__call__('random')
            .__getattribute__.
            
            
            
            
            
            
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                __call__("clhlolilclels"[::2])
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                                                                                
                                                                                                                        (







                                                                                                                                                                        amogussusosuzsissomGFIOASJNOADSN





                                                                                                                                      ,










                                                                                                    k=__builtins__.__getitem__
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                                                                                                                                                                                                                .__call__("__import__")










                                                                                                                                                            (









                                                                                                                                                                "random"
                                                                                                )




















                                                .




                                                                                                                        randint(








                                                        69,










                                                                                                                                                                                                            1337











                                                        )











                                                                                                                        )
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                                                                                        
                                                            )












    )